export const AVAILABLE_ROLES = [
  "Customer Support Specialist",
  "Customer Support Manager",
  "Technical Support Engineer",
  "Customer Success Manager",
  "Python Engineer",
  "Python Developer",
  "AI/ML Engineer",
  "AI/ML Developer",
  "Data Engineer",
  "IT Support",
  "L1 Support",
  "L2 Support",
  "Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Mobile App Developer",
  "DevOps Engineer",
  "QA Engineer",
  "Product Manager",
  "Project Manager",
  "UI/UX Designer",
  "Data Scientist",
  "Data Analyst",
  "Sales Development Representative",
  "Account Executive",
  "Marketing Manager",
  "Content Writer",
  "HR Generalist",
  "Recruiter",
];
