export const AVAILABLE_ROLES = [
  "Customer Support Specialist",
  "Customer Support Manager",
  "Technical Support Engineer",
  "Customer Success Manager",
  "Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Mobile App Developer",
  "DevOps Engineer",
  "QA Engineer",
  "Product Manager",
  "Project Manager",
  "UI/UX Designer",
  "Data Scientist",
  "Data Analyst",
  "Sales Development Representative",
  "Account Executive",
  "Marketing Manager",
  "Content Writer",
  "HR Generalist",
  "Recruiter",
];
